global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: "weather-monitoring"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "weather-analysis"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "weather-streams"
          environment: "development"

    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
